[package]
name = "asdcontrol-gnome"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/sznowicki/asdcontrol-gnome"

[dependencies]
gtk4 = "0.9.6"
rust-i18n = "3.1.4"
libc = "0.2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
